import type { Request, Response } from "express";
import { isHex } from "viem";
import { type IAgentRuntime, type Route, logger } from "@elizaos/core";
import { CacheEntry } from "../types/core";
import { getLevvaUser } from "../util/db";

interface Suggestions {
  label: string;
  text: string;
}

const FALLBACK_SUGGESTIONS: Suggestions[] = [
  {
    label: "Check My Portfolio",
    text: "Show me my current portfolio and asset breakdown",
  },
  {
    label: "Find Safe Strategies",
    text: "I want to explore safe investment strategies for steady yields",
  },
  {
    label: "Swap Tokens",
    text: "I want to swap some tokens for better opportunities",
  },
  {
    label: "Crypto News",
    text: "What's the latest news affecting DeFi and crypto markets?",
  },
  {
    label: "Strategy Recommendations",
    text: "Recommend investment strategies based on my portfolio and risk tolerance",
  },
];

async function handler(req: Request, res: Response, runtime: IAgentRuntime) {
  const { address, chainId: _chainId } = req.query;

  try {
    if (!isHex(address)) {
      throw new Error("Invalid address");
    }

    const user = (await getLevvaUser(runtime, { address }))[0];

    if (!user) {
      throw new Error("User not found");
    }

    if (!_chainId) {
      throw new Error("Chain ID is required");
    }

    const chainId = Number(_chainId);

    if (!Number.isFinite(chainId)) {
      throw new Error("Invalid chain ID");
    }

    // Check if suggestions are currently being generated
    const loadingKey = `suggestions_loading:${user.address}:${chainId}`;
    // @ts-expect-error - stateCache exists on runtime but not in interface
    const isLoading = !!runtime.stateCache.get(loadingKey);

    // Simply return cached suggestions (generated by the evaluator)
    const cached = await runtime.getCache<CacheEntry<Suggestions[]>>(
      `suggestions:${user.address}:${chainId}`
    );

    // Provide fallback suggestions if no cache exists
    const suggestions = cached?.value ?? [];

    res.status(200).json({
      success: true,
      data: {
        suggestions: isLoading
          ? []
          : !suggestions.length
            ? FALLBACK_SUGGESTIONS
            : suggestions,
        isLoading,
      },
    });
  } catch (error) {
    logger.error(error);

    res.status(500).json({
      success: false,
      error: {
        code: "SERVER_ERROR",
        message: error instanceof Error ? error.message : "Unknown error",
      },
    });
  }
}

const suggestRoute: Route = {
  name: "suggest",
  path: "/suggest",
  type: "GET",
  handler,
};

export default suggestRoute;
