export enum LEVVA_ACTIONS {
  ANALYZE_WALLET = "ANALYZE_WALLET",
  SWAP_TOKENS = "SWAP_TOKENS",
  SELECT_STRATEGY = "SELECT_STRATEGY",
  MANAGE_POSITIONS = "MANAGE_POSITIONS",
}

export enum LEVVA_SERVICE {
  LEVVA_COMMON = "levva-common",
}
